spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.springframework.jdbc=DEBUG