
SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE REVIEW_LIKES;
TRUNCATE TABLE REVIEWS;
TRUNCATE TABLE EVENTS;
TRUNCATE TABLE LIKES;
TRUNCATE TABLE FRIENDS;
TRUNCATE TABLE film_director;
TRUNCATE TABLE FILM_GENRES;
TRUNCATE TABLE FILMS;
TRUNCATE TABLE USERS;
TRUNCATE TABLE directors;
TRUNCATE TABLE GENRES;
TRUNCATE TABLE MPA;

SET REFERENTIAL_INTEGRITY TRUE;

MERGE INTO MPA (MPA_ID, NAME)
    KEY(MPA_ID)
    VALUES
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, 'R'),
        (5, 'NC-17');

MERGE INTO GENRES (GENRE_ID,  GENRE_NAME)
    KEY(GENRE_ID)
    VALUES
        (1, 'Комедия'),
        (2, 'Драма'),
        (3, 'Мультфильм'),
        (4, 'Триллер'),
        (5, 'Документальный'),
        (6, 'Боевик');
