SET REFERENTIAL_INTEGRITY FALSE;


DELETE FROM REVIEW_LIKES;
DELETE FROM REVIEWS;
DELETE FROM EVENTS;
DELETE FROM LIKES;
DELETE FROM FRIENDS;
DELETE FROM film_director;
DELETE FROM FILM_GENRES;
DELETE FROM USERS;
DELETE FROM FILMS;
DELETE FROM directors;
DELETE FROM GENRES;
DELETE FROM MPA;

SET REFERENTIAL_INTEGRITY TRUE;

ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE EVENTS ALTER COLUMN EVENT_ID RESTART WITH 1;
ALTER TABLE REVIEWS ALTER COLUMN REVIEW_ID RESTART WITH 1;
ALTER TABLE GENRES ALTER COLUMN GENRE_ID RESTART WITH 1;
ALTER TABLE MPA ALTER COLUMN MPA_ID RESTART WITH 1;
ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;
