SET REFERENTIAL_INTEGRITY FALSE;


DELETE FROM REVIEW_LIKES;
DELETE FROM REVIEWS;
DELETE FROM EVENTS;
DELETE FROM LIKES;
DELETE FROM FRIENDS;
DELETE FROM film_director;
DELETE FROM FILM_GENRES;
DELETE FROM USERS;
DELETE FROM FILMS;
DELETE FROM directors;

SET REFERENTIAL_INTEGRITY TRUE;

ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;
ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;
ALTER TABLE EVENTS ALTER COLUMN EVENT_ID RESTART WITH 1;
ALTER TABLE REVIEWS ALTER COLUMN REVIEW_ID RESTART WITH 1;
ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;

MERGE INTO MPA (MPA_ID, NAME)
    KEY(MPA_ID)
    VALUES
        (1, 'G'),
        (2, 'PG'),
        (3, 'PG-13'),
        (4, 'R'),
        (5, 'NC-17');

MERGE INTO GENRES (GENRE_ID, GENRE_NAME)
    KEY(GENRE_ID)
    VALUES
        (1, 'Комедия'),
        (2, 'Драма'),
        (3, 'Мультфильм'),
        (4, 'Триллер'),
        (5, 'Документальный'),
        (6, 'Боевик');